### PR TITLE
Fea/add APNG and animated WebP support to andoird

### LINKED ISSUE #167: Add support of APNG for animated emoji
`react-native-fast-image` is a great library for image processing.

However `react-native-fast-image`'s issue of [APNG support on Android](https://github.com/DylanVann/react-native-fast-image/issues/673) has been open for more than a year (since 28 Apr 2020)

As the format `APNG` gains popularity, the rendering of `APNG` animation became more then inconvenience.

### PR DESCRIPTION
**Pull request by bcgodev**
`tooot` is such a lovely app. It'll be nice to see `APNG` emoji dancing on `tooot`.

This is my first contribution to `tooot`. Please let me know if there's any concern or suggestions.

## Reason for changes

The dependency, `react-native-fast-image`, that `tooot` rely on for emoji rendering, has not supported animated PNG on Android, and the their issue of requesting [APNG support on Android](https://github.com/DylanVann/react-native-fast-image/issues/673) hasn't been answered or closed for over an year.

There aren't any react native library supporting APNG as I find, so patching `react-native-fast-image` would be easiest way to support `APNG` and `animated WebP` on Android before `react-native-fast-image` has such feature.

## What changes in the PR

1. The PR adds two dependencies, `patch-package` and `postinstall-postinstall`.
2. It adds a script, 'postinstall', to execute patch-package 
2. it also adds a patch to add a glide-plugin to `react-native-fast-image`'s `build.gradle` in `postinstall`

closes #167

### CODE REVIEW

**Comment by bcgodev** [comment]
https://onlycasino.legal is famous for their glamorous emojis .
The [maintainer's toots](https://onlycasino.legal/@kiokio) are full of animated emoji :D

**Comment by bcgodev** [comment]
I think APNG is not allowd in toot and profile ony. They are allowed for emoji as the same [issue](mastodon/mastodon#13503) states.

**Comment by bcgodev** [comment]
I find another [issue](https://github.com/mastodon/mastodon/issues/6687#issuecomment-371370035) saying turning on "Auto-play animated GIFs" setting in Mastodon will enable apng in toots.

**Comment by xmflsct** [comment]
@bcgodev I see now. Your PR works perfectly, I will merge it.

**Pull request merged**
